#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 21:31:08 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.8.1.zip
enableShaders=false
